dist: bionic
language: python
python:
  - "3.6"
  - "3.10"
cache: pip
script:
  - pylint django_leek --django-settings-module=django_leek.settings
  - coverage run $(which django-admin) test --pythonpath=. --settings=django_leek.settings
  - python -m coverage_shield
