# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-10 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_leek', '0004_auto_20200304_1134_squashed_0006_auto_20200305_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pickled_exception',
            field=models.BinaryField(max_length=2048, null=True),
        ),
    ]
