# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_leek', '0004_auto_20200304_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='exception',
            new_name='pickled_exception',
        ),
    ]
