# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_leek', '0005_auto_20200305_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='queued_on',
            new_name='queued_at',
        ),
    ]
